### ISSUE TITLE
Add registration url

### ISSUE THREAD

**Issue by Chilipp** [eileen-kuehn/sorse-data-filter#1]
Each event has an individual url to register as a participant. Can we add this URL here?

**Comment by eileen-kuehn** [comment]
Yes, we will! But there will be possibly several urls to register for the different deliveries.

**Comment by Chilipp** [comment]
closing this as the registration url will be added independent of the indico export (see https://github.com/eileen-kuehn/sorse-data-filter/issues/2#issuecomment-658315725)
