### ISSUE TITLE
Create links in metadata

### ISSUE THREAD

**Issue by eileen-kuehn** [eileen-kuehn/sorse-data-filter#26]
As mentioned by @Chilipp links in website metadata should be replaced by their corresponding html links.

```suggestion
instructions: "<a href='https://www.sphinx-doc.org/en/master/usage/installation.html#installation-from-pypi'>https://sphinx-doc.org</a>"
```

_Originally posted by @Chilipp in https://github.com/SORSE/sorse.github.io/pull/258#discussion_r460744095_

**Comment by eileen-kuehn** [comment]
@Chilipp, what is the reason for shortening the URL? 
Do you consider it safe in each case to abstract from this example considering the base URL only?
I currently tend to adding the link itself but keeping the text content as is. What do you think?

**Comment by Chilipp** [comment]
hey @eileen-kuehn, the reason was just that https://www.sphinx-doc.org/en/master/usage/installation.html#installation-from-pypi is quite long and does not look good on the website. But yes, I agree that we should keep the text content as is

**Comment by eileen-kuehn** [comment]
@Chilipp, we have the possibility to render the links with e.g. ``http://link-being-too-lon...`` (so cutting it in case it is too long) via CSS. What do you think?

**Comment by Chilipp** [comment]
sounds like a good idea :+1: :smiley:
